"""
Merchant & Risk Domain Data Generator

Generates synthetic data for:

    1. Fraud Alerts

Note: Merchants themselves are generated by ``merchant_generator.py``.
This generator produces the risk-monitoring layer (Fraud Alerts) that
sits on top of the Transactions dataset.
"""

from __future__ import annotations

# =====================================================================
# Standard Library
# =====================================================================

import random
from datetime import date, datetime, timedelta

# =====================================================================
# Third Party Libraries
# =====================================================================

import pandas as pd
from faker import Faker

# =====================================================================
# Project Configuration
# =====================================================================

from config.config import (
    RANDOM_SEED,
    NUM_FRAUD_ALERTS,
    TRANSACTIONS_FILE,
    EMPLOYEES_FILE,
    FRAUD_ALERTS_FILE,
    FRAUD_SOURCE_SYSTEM,
)

from config.constants import (
    ALERT_STATUS,
    ALERT_REASONS,
    MIN_FRAUD_SCORE,
    MAX_FRAUD_SCORE,
)

# =====================================================================
# Models
# =====================================================================

from models.fraud_alert import FraudAlert

# =====================================================================
# Utilities
# =====================================================================

from generators.id_generator import (
    alert_id,
)

# =====================================================================
# Logging
# =====================================================================

from config.logging_config import setup_logger

# Alert statuses considered "closed" - only these carry a resolution date
TERMINAL_ALERT_STATUSES = {

    "Resolved",

    "False Positive",

    "Closed",

}


# =====================================================================
# Risk Generator
# =====================================================================

class RiskGenerator:
    """
    Merchant & Risk Domain Generator.

    Generates:

        • Fraud Alerts
    """

    def __init__(self) -> None:

        self.logger = setup_logger(__name__)

        self.fake = Faker("en_IN")

        random.seed(RANDOM_SEED)

        self.fake.seed_instance(RANDOM_SEED)

        # ==============================================================
        # Load Parent Datasets
        # ==============================================================

        self.logger.info(
            "Loading Transaction dataset..."
        )

        self.transaction_master = pd.read_csv(
            TRANSACTIONS_FILE
        )

        self.logger.info(
            f"Loaded {len(self.transaction_master)} transactions."
        )

        self.logger.info(
            "Loading Employee dataset..."
        )

        self.employee_master = pd.read_csv(
            EMPLOYEES_FILE
        )

        self.logger.info(
            f"Loaded {len(self.employee_master)} employees."
        )

        # ==============================================================
        # Generated Objects
        # ==============================================================

        self.fraud_alerts: list[FraudAlert] = []

        self.logger.info(
            "Risk Generator initialized successfully."
        )

    # =====================================================================
    # DataFrames
    # =====================================================================

    def fraud_alerts_df(self) -> pd.DataFrame:
        """
        Return Fraud Alerts dataframe.
        """

        return pd.DataFrame(
            [alert.to_dict() for alert in self.fraud_alerts]
        )

    # =====================================================================
    # Transaction Selection
    # =====================================================================

    def _select_risky_transactions(self) -> pd.DataFrame:
        """
        Select transactions eligible to be flagged.

        Business Rules
        --------------
        • Larger transaction amounts are more likely to be flagged.
        • International and high-value channel transactions
          (RTGS, NEFT, Online Payment) are weighted higher.
        """

        transactions = self.transaction_master.copy()

        if transactions.empty:

            raise ValueError(
                "No transactions available to generate fraud alerts."
            )

        weights = transactions["amount"].clip(lower=1).astype(float)

        if "is_international" in transactions.columns:

            international_boost = transactions["is_international"].map(
                {"Yes": 5.0, "No": 1.0}
            ).fillna(1.0)

            weights = weights * international_boost

        sample_size = min(
            NUM_FRAUD_ALERTS,
            len(transactions),
        )

        selected_indices = random.choices(
            population=transactions.index.tolist(),
            weights=weights.tolist(),
            k=sample_size,
        )

        return transactions.loc[selected_indices]

    # =====================================================================
    # Fraud Alert Helper Methods
    # =====================================================================

    def _generate_fraud_score(self) -> int:
        """
        Generate a fraud score.

        Business Rule
        -------------
        Most flagged transactions turn out to be low/medium risk
        (false positives or minor anomalies); a smaller share are
        genuinely high risk.
        """

        bucket = random.choices(

            ["low", "medium", "high"],

            weights=[40, 35, 25],

            k=1,

        )[0]

        ranges = {

            "low": (MIN_FRAUD_SCORE, 39),

            "medium": (40, 69),

            "high": (70, MAX_FRAUD_SCORE),

        }

        minimum, maximum = ranges[bucket]

        return random.randint(minimum, maximum)

    def _generate_alert_reason(self) -> str:
        """
        Generate alert reason.
        """

        return random.choice(ALERT_REASONS)

    def _generate_alert_status(self) -> str:
        """
        Generate alert status.
        """

        return random.choices(

            ALERT_STATUS,

            weights=[
                15,     # Open
                20,     # Under Investigation
                40,     # Resolved
                15,     # False Positive
                10,     # Closed
            ],

            k=1,

        )[0]

    def _generate_alert_timestamp(
        self,
        transaction_timestamp: str,
    ) -> datetime:
        """
        Generate the alert timestamp, shortly after the transaction.
        """

        try:

            base_timestamp = pd.to_datetime(
                transaction_timestamp
            ).to_pydatetime()

        except (ValueError, TypeError):

            base_timestamp = datetime.now()

        delay_minutes = random.randint(1, 240)

        return base_timestamp + timedelta(minutes=delay_minutes)

    def _select_assignee(
        self,
        alert_status: str,
    ) -> tuple[str | None, str | None]:
        """
        Select an employee to assign the alert to.

        Returns
        -------
        Tuple of (assigned_to name, assignee_emp_id), or (None, None)
        for alerts that have not yet been triaged.
        """

        if alert_status == "Open":

            return (None, None)

        risk_team = self.employee_master[

            self.employee_master["department"].isin(
                ["Risk", "Compliance"]
            )

            & (self.employee_master["employee_status"] == "Active")

        ]

        pool = risk_team if not risk_team.empty else self.employee_master

        if pool.empty:

            return (None, None)

        employee = pool.sample(n=1).iloc[0]

        assigned_to = (
            f"{employee['first_name']} {employee['last_name']}"
        )

        return (assigned_to, employee["employee_id"])

    def _generate_resolution_date(
        self,
        alert_status: str,
        alert_timestamp: datetime,
    ) -> date | None:
        """
        Generate resolution date for closed-out alerts only.
        """

        if alert_status not in TERMINAL_ALERT_STATUSES:

            return None

        return self.fake.date_between(
            start_date=alert_timestamp.date(),
            end_date=min(
                alert_timestamp.date() + timedelta(days=30),
                date.today(),
            ),
        )

    # =====================================================================
    # Generate Fraud Alerts
    # =====================================================================

    def generate_fraud_alerts(self) -> None:
        """
        Generate Fraud Alert data.
        """

        self.logger.info(
            "Generating Fraud Alerts..."
        )

        risky_transactions = self._select_risky_transactions()

        for _, transaction in risky_transactions.iterrows():

            alert_status = self._generate_alert_status()

            alert_timestamp = self._generate_alert_timestamp(
                transaction["transaction_timestamp"]
            )

            assigned_to, assignee_emp_id = self._select_assignee(
                alert_status
            )

            alert = FraudAlert(

                alert_id=alert_id(),

                transaction_id=transaction["transaction_id"],

                fraud_score=self._generate_fraud_score(),

                alert_reason=self._generate_alert_reason(),

                alert_status=alert_status,

                alert_timestamp=alert_timestamp,

                assigned_to=assigned_to,

                assignee_emp_id=assignee_emp_id,

                resolution_date=self._generate_resolution_date(
                    alert_status,
                    alert_timestamp,
                ),

                created_at=datetime.now(),

                updated_at=None,

                source_system=FRAUD_SOURCE_SYSTEM,

            )

            self.fraud_alerts.append(alert)

        self.logger.info(
            f"{len(self.fraud_alerts)} Fraud Alerts generated successfully."
        )

    # =====================================================================
    # Validate Fraud Alerts
    # =====================================================================

    def validate_fraud_alerts(self) -> bool:
        """
        Validate Fraud Alerts dataset.
        """

        self.logger.info(
            "Validating Fraud Alerts..."
        )

        df = self.fraud_alerts_df()

        if df.empty:

            self.logger.error(
                "Fraud Alerts dataframe is empty."
            )

            return False

        if df["alert_id"].duplicated().any():

            self.logger.error(
                "Duplicate Alert IDs detected."
            )

            return False

        valid_transactions = set(
            self.transaction_master["transaction_id"]
        )

        if (~df["transaction_id"].isin(valid_transactions)).any():

            self.logger.error(
                "Invalid Transaction IDs detected."
            )

            return False

        if (
            (df["fraud_score"] < MIN_FRAUD_SCORE)
            | (df["fraud_score"] > MAX_FRAUD_SCORE)
        ).any():

            self.logger.error(
                "Fraud score out of valid range detected."
            )

            return False

        mandatory_columns = [

            "alert_id",

            "transaction_id",

            "fraud_score",

            "alert_reason",

            "alert_status",

            "alert_timestamp",

        ]

        for column in mandatory_columns:

            if df[column].isnull().any():

                self.logger.error(
                    f"Null values found in {column}."
                )

                return False

        self.logger.info(
            "Fraud Alert validation completed successfully."
        )

        return True

    # =====================================================================
    # Export Fraud Alerts
    # =====================================================================

    def export_fraud_alerts(self) -> None:
        """
        Export Fraud Alerts dataset.
        """

        self.logger.info(
            "Exporting Fraud Alerts..."
        )

        self.fraud_alerts_df().to_csv(

            FRAUD_ALERTS_FILE,

            index=False,

        )

        self.logger.info(
            f"Fraud Alerts exported successfully to {FRAUD_ALERTS_FILE}"
        )

    # =====================================================================
    # Validate All
    # =====================================================================

    def validate_all(self) -> bool:
        """
        Validate all generated Risk datasets.
        """

        self.logger.info(
            "Running Validation..."
        )

        validations = [

            self.validate_fraud_alerts(),

        ]

        if all(validations):

            self.logger.info(
                "Validation Successful."
            )

            return True

        self.logger.error(
            "Validation Failed."
        )

        return False

    # =====================================================================
    # Export All
    # =====================================================================

    def export_all(self) -> None:
        """
        Export all Risk datasets.
        """

        self.logger.info(
            "Exporting datasets..."
        )

        self.export_fraud_alerts()

        self.logger.info(
            "Export completed successfully."
        )

    # =====================================================================
    # Summary
    # =====================================================================

    def summary(self) -> None:
        """
        Display Risk Generation Summary.
        """

        self.logger.info("=" * 70)

        self.logger.info(
            "Risk Generation Summary"
        )

        self.logger.info(
            f"Fraud Alerts Generated  : {len(self.fraud_alerts)}"
        )

        self.logger.info("=" * 70)

    # =====================================================================
    # Pipeline Execution
    # =====================================================================

    def run(self) -> None:
        """
        Execute Risk Generator.
        """

        try:

            self.logger.info("=" * 80)

            self.logger.info(
                "Starting Risk Generator..."
            )

            self.generate_fraud_alerts()

            self.summary()

            if not self.validate_all():

                raise ValueError(
                    "Validation Failed."
                )

            self.export_all()

            self.logger.info(
                "Risk Generator completed successfully."
            )

            self.logger.info("=" * 80)

        except Exception as ex:

            self.logger.exception(ex)

            raise


# =====================================================================
# Main
# =====================================================================

if __name__ == "__main__":
    print("Starting Risk Generator...")

    generator = RiskGenerator()

    print("Generator created.")

    generator.run()

    print("Pipeline finished.")
