CREATE OR REPLACE TABLE ABC_BANK.STG.CUST_CUSTOMER_ADDRESSES
(
    ADDRESS_ID          VARCHAR(20)        NOT NULL,
    CUSTOMER_ID         VARCHAR(20)        NOT NULL,

    ADDRESS_TYPE        VARCHAR(20)        NOT NULL,

    ADDRESS_LINE1       VARCHAR(200)       NOT NULL,
    ADDRESS_LINE2       VARCHAR(200),

    CITY                VARCHAR(100)       NOT NULL,
    STATE               VARCHAR(100)       NOT NULL,
    POSTAL_CODE         VARCHAR(15)        NOT NULL,
    COUNTRY             VARCHAR(100)       NOT NULL,

    IS_CURRENT          BOOLEAN            NOT NULL,

    EFFECTIVE_DATE      DATE               NOT NULL,
    EXPIRY_DATE         DATE,

    CONSTRAINT PK_CUSTOMER_ADDRESSES
        PRIMARY KEY (ADDRESS_ID),

    CONSTRAINT FK_CUSTOMER_ADDRESSES_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUST_CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT CHK_ADDRESS_TYPE
        CHECK (UPPER(ADDRESS_TYPE) IN ('HOME','OFFICE','MAILING','PERMANENT')),

    CONSTRAINT CHK_EFFECTIVE_DATE
        CHECK (EXPIRY_DATE IS NULL OR EXPIRY_DATE >= EFFECTIVE_DATE)
);