CREATE OR REPLACE TABLE ABC_BANK.STG.CUST_KYC
(
    CUSTOMER_ID             VARCHAR(20)    NOT NULL,

    PAN_NUMBER              VARCHAR(10)    NOT NULL,
    AADHAAR_NUMBER          VARCHAR(12)    NOT NULL,

    PAN_VERIFIED            BOOLEAN        NOT NULL,
    AADHAAR_VERIFIED        BOOLEAN        NOT NULL,
    ADDRESS_VERIFIED        BOOLEAN        NOT NULL,

    KYC_STATUS              VARCHAR(20)    NOT NULL,

    VERIFICATION_DATE       DATE,
	BATCH_ID                TIMESTAMP_NTZ,
	BATCH_DATE          DATE,
	PIPELINE_RUN_ID		VARCHAR(20),
	DATA_SOURCE			VARCHAR(50)
);