CREATE OR REPLACE TABLE ABC_BANK.STG.RISK_FRAUD_ALERTS
(
    ALERT_ID                  VARCHAR(20)       NOT NULL,

    TRANSACTION_ID            VARCHAR(20)       NOT NULL,

    FRAUD_SCORE               NUMBER(5,2)       NOT NULL,

    ALERT_REASON              VARCHAR(255)      NOT NULL,

    ALERT_STATUS              VARCHAR(20)       NOT NULL,

    ALERT_TIMESTAMP           TIMESTAMP_NTZ     NOT NULL,

    ASSIGNED_TO               VARCHAR(100),

    ASSIGNEE_EMP_ID           VARCHAR(20),

    RESOLUTION_DATE           DATE,

    CREATED_AT                TIMESTAMP_NTZ     DEFAULT CURRENT_TIMESTAMP(),

    UPDATED_AT                TIMESTAMP_NTZ,

    SOURCE_SYSTEM             VARCHAR(50)       DEFAULT 'Fraud Detection System',

    BATCH_ID                  VARCHAR(50),

    CONSTRAINT PK_FRAUD_ALERTS
        PRIMARY KEY (ALERT_ID),

    CONSTRAINT FK_ALERT_TRANSACTION
        FOREIGN KEY (TRANSACTION_ID)
        REFERENCES ABC_BANK.STG.BANK_TRANSACTIONS (TRANSACTION_ID),

    CONSTRAINT FK_ALERT_EMPLOYEE
        FOREIGN KEY (ASSIGNEE_EMP_ID)
        REFERENCES ABC_BANK.STG.ORG_EMPLOYEES (EMPLOYEE_ID),

    CONSTRAINT CHK_FRAUD_SCORE
        CHECK (FRAUD_SCORE BETWEEN 0 AND 100),

    CONSTRAINT CHK_ALERT_STATUS
        CHECK (ALERT_STATUS IN
        (
            'Open',
            'Under Investigation',
            'Resolved',
            'False Positive',
            'Closed'
        ))
);