CREATE OR REPLACE TABLE banking_data_processing.silver.BANK_CARDS
(
    CARD_ID                 VARCHAR(20)        NOT NULL,

    ACCOUNT_ID              VARCHAR(20)        NOT NULL,

    CARD_NUMBER             VARCHAR(19)        NOT NULL,

    CARD_TYPE               VARCHAR(20)        NOT NULL,

    NETWORK                 VARCHAR(20)        NOT NULL,

    ISSUE_DATE              DATE               NOT NULL,

    EXPIRY_DATE             DATE               NOT NULL,

    CREDIT_LIMIT            DECIMAL(15,2),

    CARD_STATUS             VARCHAR(20)        NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50),
	BATCH_DATE          DATE,
	PIPELINE_RUN_ID		VARCHAR(100),
	DATA_SOURCE			VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_CARDS
        PRIMARY KEY (CARD_ID),

    CONSTRAINT UQ_CARD_NUMBER
        UNIQUE (CARD_NUMBER),

    CONSTRAINT FK_CARDS_ACCOUNTS
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES BANK_ACCOUNTS(ACCOUNT_ID)
);