CREATE OR REPLACE TABLE banking_data_processing.silver.CUST_KYC
(
    CUSTOMER_ID             VARCHAR(20)    NOT NULL,

    PAN_NUMBER              VARCHAR(10)    NOT NULL,
    AADHAAR_NUMBER          VARCHAR(12)    NOT NULL,

    PAN_VERIFIED            BOOLEAN        NOT NULL,
    AADHAAR_VERIFIED        BOOLEAN        NOT NULL,
    ADDRESS_VERIFIED        BOOLEAN        NOT NULL,

    KYC_STATUS              VARCHAR(20)    NOT NULL,
	BATCH_DATE          DATE,
	PIPELINE_RUN_ID		VARCHAR(100),
	DATA_SOURCE			VARCHAR(50),
	LOAD_TIMESTAMP       TIMESTAMP,

    CONSTRAINT PK_KYC
        PRIMARY KEY (CUSTOMER_ID),

    CONSTRAINT FK_KYC_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUST_CUSTOMERS(CUSTOMER_ID)
);