CREATE OR REPLACE TABLE banking_data_processing.silver.ORG_BRANCHES
(
    BRANCH_ID               VARCHAR(20)        NOT NULL,

    BRANCH_NAME             VARCHAR(100)       NOT NULL,

    CITY                    VARCHAR(100)       NOT NULL,

    STATE                   VARCHAR(100)       NOT NULL,

    COUNTRY                 VARCHAR(100)       NOT NULL,

    ZIP_CODE                VARCHAR(15)        NOT NULL,

    MANAGER_EMPLOYEE_ID     VARCHAR(20),

    OPENED_DATE             DATE               NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50),
	BATCH_DATE         		DATE,
	PIPELINE_RUN_ID			VARCHAR(100),
	DATA_SOURCE				VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_BRANCHES
        PRIMARY KEY (BRANCH_ID)
);


ALTER TABLE banking_data_processing.silver.ORG_BRANCHES
ADD CONSTRAINT FK_BRANCH_MANAGER
FOREIGN KEY (MANAGER_EMPLOYEE_ID)
REFERENCES ORG_EMPLOYEES(EMPLOYEE_ID);