CREATE OR REPLACE TABLE banking_data_processing.silver.LOAN_LOAN_COLLATERAL
(
    COLLATERAL_ID           VARCHAR(20)        NOT NULL,

    LOAN_ID                 VARCHAR(20)        NOT NULL,

    ASSET_TYPE              VARCHAR(30)        NOT NULL,

    ASSET_VALUE             DECIMAL(15,2)       NOT NULL,

    VALUATION_DATE          DATE               NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50)        ,
	BATCH_DATE         		DATE,
	PIPELINE_RUN_ID			VARCHAR(100),
	DATA_SOURCE				VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_LOAN_COLLATERAL
        PRIMARY KEY (COLLATERAL_ID),

    CONSTRAINT FK_COLLATERAL_LOAN
        FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_LOANS(LOAN_ID)
);