CREATE OR REPLACE TABLE banking_data_processing.silver.RISK_FRAUD_ALERTS
(
    ALERT_ID                  VARCHAR(20)       NOT NULL,

    TRANSACTION_ID            VARCHAR(20)       NOT NULL,

    FRAUD_SCORE               DECIMAL(5,2)       NOT NULL,

    ALERT_REASON              VARCHAR(255)      NOT NULL,

    ALERT_STATUS              VARCHAR(20)       NOT NULL,

    ALERT_TIMESTAMP           TIMESTAMP_NTZ     NOT NULL,

    ASSIGNED_TO               VARCHAR(100),

    ASSIGNEE_EMP_ID           VARCHAR(20),

    RESOLUTION_DATE           DATE,

    CREATED_AT                TIMESTAMP_NTZ     ,

    UPDATED_AT                TIMESTAMP_NTZ,

    SOURCE_SYSTEM             VARCHAR(50),

	BATCH_DATE          	  DATE,
	PIPELINE_RUN_ID			  VARCHAR(100),
	DATA_SOURCE				  VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_FRAUD_ALERTS
        PRIMARY KEY (ALERT_ID),

    CONSTRAINT FK_ALERT_TRANSACTION
        FOREIGN KEY (TRANSACTION_ID)
        REFERENCES banking_data_processing.silver.BANK_TRANSACTIONS (TRANSACTION_ID),

    CONSTRAINT FK_ALERT_EMPLOYEE
        FOREIGN KEY (ASSIGNEE_EMP_ID)
        REFERENCES banking_data_processing.silver.ORG_EMPLOYEES (EMPLOYEE_ID)
);