CREATE OR REPLACE TABLE banking_data_processing.silver.BANK_MERCHANTS
(
    MERCHANT_ID                VARCHAR(20)        NOT NULL,

    MERCHANT_NAME              VARCHAR(150)       NOT NULL,

    MERCHANT_CATEGORY          VARCHAR(50)        NOT NULL,

    MERCHANT_TYPE		       VARCHAR(200),

    CITY                       VARCHAR(100)       NOT NULL,

    STATE                      VARCHAR(100)       NOT NULL,

    COUNTRY                    VARCHAR(100)       NOT NULL,

    MERCHANT_STATUS            VARCHAR(20)        NOT NULL,
	
	ACCEPTS_UPI				   VARCHAR(3),
	
	ACCEPTS_CARDS			   VARCHAR(3),
	
	AVG_TICKET_SIZE			   DECIMAL(15,2),
	
	ONBOARDING_DATE			   DATE,

    CREATED_AT                 TIMESTAMP_NTZ      ,

    UPDATED_AT                 TIMESTAMP_NTZ,

    SOURCE_SYSTEM              VARCHAR(50),

	BATCH_DATE          	   DATE,
	PIPELINE_RUN_ID			   VARCHAR(100),
	DATA_SOURCE				   VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_MERCHANTS
        PRIMARY KEY (MERCHANT_ID)
);