CREATE OR REPLACE TABLE banking_data_processing.silver.BANK_TRANSACTIONS
(
    TRANSACTION_ID              VARCHAR(20)        NOT NULL,

    ACCOUNT_ID                  VARCHAR(20)        NOT NULL,

    MERCHANT_ID                 VARCHAR(20),

    TRANSACTION_TIMESTAMP       TIMESTAMP_NTZ      NOT NULL,

    TRANSACTION_TYPE            VARCHAR(20)        NOT NULL,

    AMOUNT                      DECIMAL(18,2)       NOT NULL,

    CURRENCY                    VARCHAR(3)         NOT NULL,

    TRANSACTION_CHANNEL         VARCHAR(30)        NOT NULL,

    TRANSACTION_STATUS          VARCHAR(20)        NOT NULL,

    REFERENCE_NUMBER            VARCHAR(50)        NOT NULL,

    CREATED_AT                  TIMESTAMP_NTZ,
    UPDATED_AT                  TIMESTAMP_NTZ,
    SOURCE_SYSTEM               VARCHAR(50),
	BATCH_DATE                  DATE,
	PIPELINE_RUN_ID		VARCHAR(100),
	DATA_SOURCE			VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_TRANSACTIONS
        PRIMARY KEY (TRANSACTION_ID),

    CONSTRAINT UQ_REFERENCE_NUMBER
        UNIQUE (REFERENCE_NUMBER),

    CONSTRAINT FK_TRANSACTIONS_ACCOUNTS
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES BANK_ACCOUNTS(ACCOUNT_ID),

    CONSTRAINT FK_TRANSACTIONS_MERCHANTS
        FOREIGN KEY (MERCHANT_ID)
        REFERENCES BANK_MERCHANTS(MERCHANT_ID)
);