CREATE OR REPLACE TABLE banking_data_processing.silver.CUST_CUSTOMER_ADDRESSES
(
    ADDRESS_ID          VARCHAR(20)        NOT NULL,
    CUSTOMER_ID         VARCHAR(20)        NOT NULL,

    ADDRESS_TYPE        VARCHAR(20)        NOT NULL,

    ADDRESS_LINE1       VARCHAR(200)       NOT NULL,
    ADDRESS_LINE2       VARCHAR(200),

    CITY                VARCHAR(100)       NOT NULL,
    STATE               VARCHAR(100)       NOT NULL,
    POSTAL_CODE         VARCHAR(15)        NOT NULL,
    COUNTRY             VARCHAR(100)       NOT NULL,

    SOURCE_IS_CURRENT          BOOLEAN     NOT NULL,

    SOURCE_EFFECTIVE_DATE      DATE        NOT NULL,
    SOURCE_EXPIRY_DATE         DATE,
	BATCH_DATE          DATE,
	PIPELINE_RUN_ID		VARCHAR(100),
	DATA_SOURCE			VARCHAR(50),
    EFFECTIVE_FROM      TIMESTAMP NOT NULL,
    EFFECTIVE_TO        TIMESTAMP,
	IS_CURRENT			BOOLEAN     NOT NULL,
    LOAD_TIMESTAMP      TIMESTAMP NOT NULL,

    CONSTRAINT PK_CUSTOMER_ADDRESSES
        PRIMARY KEY (ADDRESS_ID),

    CONSTRAINT FK_CUSTOMER_ADDRESSES_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUST_CUSTOMERS(CUSTOMER_ID)
);