CREATE OR REPLACE TABLE banking_data_processing.silver.LOAN_LOANS
(
    LOAN_ID                 VARCHAR(20)        NOT NULL,
	LOAN_APPLICATION_ID 	VARCHAR(20),
    CUSTOMER_ID             VARCHAR(20)        NOT NULL,

    LOAN_TYPE               VARCHAR(30)        NOT NULL,

    PRINCIPAL_AMOUNT        DECIMAL(15,2)       NOT NULL,

    INTEREST_RATE           DECIMAL(5,2)        NOT NULL,

    TENURE_MONTHS           DECIMAL(4,0)        NOT NULL,

    EMI_AMOUNT              DECIMAL(15,2)       NOT NULL,

    LOAN_STATUS             VARCHAR(20)        NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50)        ,
	BATCH_DATE          	DATE,
	PIPELINE_RUN_ID			VARCHAR(100),
	DATA_SOURCE				VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_LOANS
        PRIMARY KEY (LOAN_ID),

	CONSTRAINT FK_LOANS_APPLICATION
		FOREIGN KEY (LOAN_APPLICATION_ID)
		REFERENCES LOAN_LOAN_APPLICATIONS(APPLICATION_ID),

    CONSTRAINT FK_LOANS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUST_CUSTOMERS(CUSTOMER_ID)
);