CREATE OR REPLACE TABLE banking_data_processing.silver.LOAN_LOAN_APPLICATIONS
(
    APPLICATION_ID          VARCHAR(20)        NOT NULL,

    CUSTOMER_ID             VARCHAR(20)        NOT NULL,

    APPLICATION_DATE        DATE               NOT NULL,

    REQUESTED_AMOUNT        DECIMAL(15,2)       NOT NULL,

    APPROVAL_STATUS         VARCHAR(20)        NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50),
	BATCH_DATE          	DATE,
	PIPELINE_RUN_ID			VARCHAR(100),
	DATA_SOURCE				VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_LOAN_APPLICATIONS
        PRIMARY KEY (APPLICATION_ID),

    CONSTRAINT FK_LOAN_APPLICATION_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUST_CUSTOMERS(CUSTOMER_ID)
);