CREATE OR REPLACE TABLE banking_data_processing.silver.BANK_ACCOUNTS
(
    ACCOUNT_ID              VARCHAR(20)        NOT NULL,
    CUSTOMER_ID             VARCHAR(20)        NOT NULL,
    BRANCH_ID               VARCHAR(20)        NOT NULL,

    ACCOUNT_NUMBER          VARCHAR(20)        NOT NULL,

    ACCOUNT_TYPE            VARCHAR(20),

    CURRENCY                VARCHAR(3)         NOT NULL,

    OPEN_DATE               DATE               NOT NULL,

    CURRENT_BALANCE         DECIMAL(18,2)       NOT NULL,

    ACCOUNT_STATUS          VARCHAR(20)        NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50),
	BATCH_DATE          	DATE,
	PIPELINE_RUN_ID			VARCHAR(100),
	DATA_SOURCE				VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

   CONSTRAINT PK_ACCOUNTS
        PRIMARY KEY (ACCOUNT_ID),

    CONSTRAINT UQ_ACCOUNT_NUMBER
        UNIQUE (ACCOUNT_NUMBER),

    CONSTRAINT FK_ACCOUNTS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUST_CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT FK_ACCOUNTS_BRANCHES
        FOREIGN KEY (BRANCH_ID)
        REFERENCES ORG_BRANCHES(BRANCH_ID)
);