CREATE OR REPLACE TABLE banking_data_processing.silver.ORG_EMPLOYEES
(
    EMPLOYEE_ID             VARCHAR(20)        NOT NULL,

    BRANCH_ID               VARCHAR(20)        NOT NULL,

    FIRST_NAME              VARCHAR(50)        NOT NULL,

    LAST_NAME               VARCHAR(50)        NOT NULL,

    DESIGNATION             VARCHAR(50)        NOT NULL,

    DEPARTMENT              VARCHAR(50)        NOT NULL,

    HIRE_DATE               DATE               NOT NULL,

    SALARY                  DECIMAL(12,2)       NOT NULL,

    EMPLOYEE_STATUS         VARCHAR(20)        NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50),
	BATCH_DATE         		DATE,
	PIPELINE_RUN_ID			VARCHAR(100),
	DATA_SOURCE				VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP	 		TIMESTAMP,	

    CONSTRAINT PK_EMPLOYEES
        PRIMARY KEY (EMPLOYEE_ID),

    CONSTRAINT FK_EMPLOYEE_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES ORG_BRANCHES(BRANCH_ID)
);