CREATE OR REPLACE TABLE banking_data_processing.silver.LOAN_LOAN_REPAYMENTS
(
    REPAYMENT_ID            VARCHAR(20)        NOT NULL,

    LOAN_ID                 VARCHAR(20)        NOT NULL,

    PAYMENT_DATE            DATE               NOT NULL,

    AMOUNT_PAID             DECIMAL(15,2)       NOT NULL,

    PAYMENT_MODE            VARCHAR(20)        NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      ,
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50)        ,
	BATCH_DATE          	DATE,
	PIPELINE_RUN_ID			VARCHAR(100),
	DATA_SOURCE				VARCHAR(50),
	IS_CURRENT				BOOLEAN, 
	EFFECTIVE_FROM			TIMESTAMP, 
	EFFECTIVE_TO			TIMESTAMP, 
	LOAD_TIMESTAMP			TIMESTAMP,	

    CONSTRAINT PK_LOAN_REPAYMENTS
        PRIMARY KEY (REPAYMENT_ID),

    CONSTRAINT FK_REPAYMENT_LOAN
        FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_LOANS(LOAN_ID)
);