# Databricks notebook source
# DBTITLE 1,Creating DIM_CUSTOMER
#Creating DIM_CUSTOMER
create_dim_customers = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.dim_customer
USING DELTA
WITH STG_CUST_CUSTOMERS AS 
(
	SELECT DISTINCT 
	CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME,
	DOB,
	GENDER,
	EMAIL,
	PHONE,
	OCCUPATION,
	ANNUAL_INCOME,
	CUSTOMER_SINCE,
	RISK_RATING,
	CUSTOMER_STATUS,
	CREATED_AT,
	UPDATED_AT,
	SOURCE_SYSTEM,
	BATCH_DATE
	FROM banking_data_processing.silver.cust_customers
	WHERE IS_CURRENT = TRUE
),

STG_CUST_ADDRESS AS 
(
    SELECT DISTINCT 
    ADDRESS_ID,
    CUSTOMER_ID,
    ADDRESS_TYPE,
    ADDRESS_LINE1,
    ADDRESS_LINE2,
    CITY,
    STATE,
    POSTAL_CODE,
    COUNTRY,
    BATCH_DATE
    FROM banking_data_processing.silver.cust_customer_addresses
	WHERE IS_CURRENT = TRUE
),

STG_CUST_KYC AS 
(
    SELECT DISTINCT
    CUSTOMER_ID,
    PAN_NUMBER,
    AADHAAR_NUMBER,
    PAN_VERIFIED,
    AADHAAR_VERIFIED,
    ADDRESS_VERIFIED,
    KYC_STATUS,
    BATCH_DATE
    FROM banking_data_processing.silver.cust_kyc
)

SELECT DISTINCT
CUST.CUSTOMER_ID,
CONCAT(TRIM(CUST.FIRST_NAME), ' ', TRIM(CUST.LAST_NAME)) AS CUSTOMER_NAME,
DATE(CUST.DOB) AS CUSTOMER_DATE_OF_BIRTH,
CUST.GENDER,
CUST.EMAIL,
CUST.PHONE,
TRIM(CUST.OCCUPATION) AS OCCUPATION,
CUST.ANNUAL_INCOME,
CUST.CUSTOMER_SINCE,
CUST.RISK_RATING,
UPPER(TRIM(CUST.CUSTOMER_STATUS)) AS CUSTOMER_STATUS,
CUST.CREATED_AT AS CUST_CREATED_AT,
CUST.UPDATED_AT AS CUST_UPDATED_AT,
CUST.BATCH_DATE AS CUST_BATCH_DATE,
ADD.ADDRESS_ID,
ADD.ADDRESS_TYPE,
ADD.ADDRESS_LINE1,
ADD.ADDRESS_LINE2,
ADD.CITY,
ADD.STATE,
ADD.POSTAL_CODE,
ADD.COUNTRY,
ADD.BATCH_DATE AS ADD_BATCH_DATE,
KYC.AADHAAR_NUMBER,
KYC.PAN_VERIFIED,
KYC.AADHAAR_VERIFIED,
KYC.ADDRESS_VERIFIED,
KYC.KYC_STATUS,
KYC.BATCH_DATE AS KYC_BATCH_DATE
FROM STG_CUST_CUSTOMERS CUST

LEFT JOIN STG_CUST_ADDRESS ADD ON CUST.CUSTOMER_ID = ADD.CUSTOMER_ID

LEFT JOIN STG_CUST_KYC KYC ON CUST.CUSTOMER_ID = KYC.CUSTOMER_ID
;   
""")


# COMMAND ----------

# DBTITLE 1,Creating DIM_ACCOUNT
#Creating DIM_ACCOUNT
create_dim_account = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.dim_account
USING DELTA
WITH STG_ACCOUNTS AS 
(
	SELECT DISTINCT 
	ACCOUNT_ID,
	CUSTOMER_ID,
	BRANCH_ID,
	ACCOUNT_NUMBER,
	ACCOUNT_TYPE,
	CURRENCY,
	OPEN_DATE,
	CURRENT_BALANCE,
	ACCOUNT_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.bank_accounts
	WHERE IS_CURRENT = TRUE
),

STG_CUSTOMERS AS 
(
	SELECT DISTINCT 
	CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE,
	OCCUPATION,
	ANNUAL_INCOME,
	CUSTOMER_SINCE,
	RISK_RATING,
	CUSTOMER_STATUS,
	BATCH_DATE
	FROM banking_data_processing.silver.cust_customers
	WHERE IS_CURRENT = TRUE
),

STG_CARDS AS 
(
    SELECT DISTINCT 
	CARD_ID,
	ACCOUNT_ID,
	CARD_NUMBER,
	CARD_TYPE,
	NETWORK,
	ISSUE_DATE,
	EXPIRY_DATE,
	CREDIT_LIMIT,
	CARD_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
    FROM banking_data_processing.silver.bank_cards
	WHERE IS_CURRENT = TRUE
),

STG_MERCHANTS AS 
(
    SELECT DISTINCT
	MERCHANT_ID,
	MERCHANT_NAME,
	MERCHANT_CATEGORY,
	MERCHANT_TYPE,
	CITY,
	STATE,
	COUNTRY,
	MERCHANT_STATUS,
	ACCEPTS_UPI,
	ACCEPTS_CARDS,
	AVG_TICKET_SIZE,
	ONBOARDING_DATE,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
    FROM banking_data_processing.silver.bank_merchants
	WHERE IS_CURRENT = TRUE
),

STG_BRANCHES AS 
(
SELECT DISTINCT 
	OB.BRANCH_ID,
	BRANCH_NAME,
	CITY,
	STATE,
	COUNTRY,
	ZIP_CODE,
	SE.EMPLOYEE_ID AS MANAGER_EMPLOYEE_ID,
	CONCAT(TRIM(SE.FIRST_NAME), ' ', TRIM(SE.LAST_NAME)) AS MANAGER_NAME
	FROM banking_data_processing.silver.org_branches OB
	
	LEFT JOIN 
	(
		SELECT DISTINCT 
		EMPLOYEE_ID, BRANCH_ID, FIRST_NAME, LAST_NAME, DESIGNATION 
		FROM banking_data_processing.silver.org_employees WHERE UPPER(TRIM(DESIGNATION)) = 'MANAGER'
	) SE 
	ON SE.BRANCH_ID = OB.BRANCH_ID
	
	WHERE OB.IS_CURRENT = TRUE
),

STG_TRANSACTIONS AS 
(
	SELECT DISTINCT 
	ACCOUNT_ID,
	MERCHANT_ID
	FROM banking_data_processing.silver.bank_transactions
 	WHERE IS_CURRENT = TRUE
)

SELECT DISTINCT 
ACC.ACCOUNT_ID,
ACC.ACCOUNT_NUMBER,
CUST.CUSTOMER_ID,
CONCAT(TRIM(CUST.FIRST_NAME), ' ', TRIM(CUST.LAST_NAME)) AS CUSTOMER_NAME,
CUST.EMAIL,
CUST.PHONE,
CUST.CUSTOMER_SINCE,
CUST.RISK_RATING,
CUST.CUSTOMER_STATUS,
ACC.ACCOUNT_TYPE,
ACC.CURRENCY,
ACC.OPEN_DATE,
ACC.CURRENT_BALANCE,
ACC.ACCOUNT_STATUS,
ACC.CREATED_AT AS ACC_CREATED_AT,
ACC.UPDATED_AT AS ACC_UPDATED_AT,
ACC.BATCH_DATE AS ACC_BATCH_DATE,
CUST.BATCH_DATE AS CUST_BATCH_DATE,
CARD.CARD_ID,
CARD.CARD_NUMBER,
CARD.CARD_TYPE,
CARD.NETWORK,
CARD.ISSUE_DATE,
CARD.EXPIRY_DATE,
CARD.CREDIT_LIMIT,
CARD.CARD_STATUS,
CARD.CREATED_AT AS CARD_CREATED_AT,
CARD.UPDATED_AT AS CARD_UPDATED_AT,
CARD.BATCH_DATE AS CARD_BATCH_DATE,
MER.MERCHANT_ID,
MER.MERCHANT_NAME,
MER.MERCHANT_CATEGORY,
MER.MERCHANT_TYPE,
MER.CITY AS MERCHANT_CITY,
MER.STATE AS MERCHANT_STATE,
MER.COUNTRY AS MERCHANT_COUNTRY,
MER.MERCHANT_STATUS,
MER.ACCEPTS_UPI,
MER.ACCEPTS_CARDS,
MER.AVG_TICKET_SIZE,
MER.ONBOARDING_DATE,
MER.CREATED_AT AS MERCHANT_CREATED_AT,
MER.UPDATED_AT AS MERCHANT_UPDATED_AT,
MER.BATCH_DATE AS MERCHANT_BATCH_DATE,
BRANCH.BRANCH_ID,
BRANCH.BRANCH_NAME,
BRANCH.CITY AS BRANCH_CITY,
BRANCH.STATE AS BRANCH_STATE,
BRANCH.COUNTRY AS BRANCH_COUNTRY,
BRANCH.ZIP_CODE AS BRANCH_ZIP_CODE,
BRANCH.MANAGER_EMPLOYEE_ID,
BRANCH.MANAGER_NAME

FROM STG_ACCOUNTS ACC

LEFT JOIN STG_CUSTOMERS CUST ON CUST.CUSTOMER_ID = ACC.CUSTOMER_ID

LEFT JOIN STG_CARDS CARD ON CARD.ACCOUNT_ID = ACC.ACCOUNT_ID

LEFT JOIN STG_TRANSACTIONS TRANSAC ON TRANSAC.ACCOUNT_ID = ACC.ACCOUNT_ID

LEFT JOIN STG_MERCHANTS MER ON MER.MERCHANT_ID = TRANSAC.MERCHANT_ID

LEFT JOIN STG_BRANCHES BRANCH ON BRANCH.BRANCH_ID = ACC.BRANCH_ID
;   
""")


# COMMAND ----------

# DBTITLE 1,Creating FACT_TRANSACTIONS
#Creating FACT_TRANSACTIONS
create_fact_transactions = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.fact_transactions
USING DELTA
WITH STG_ACCOUNTS AS 
(
	SELECT DISTINCT 
	ACCOUNT_ID,
	CUSTOMER_ID,
	BRANCH_ID,
	ACCOUNT_NUMBER,
	ACCOUNT_TYPE,
	CURRENCY,
	OPEN_DATE,
	CURRENT_BALANCE,
	ACCOUNT_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.bank_accounts
	WHERE IS_CURRENT = TRUE
),

STG_MERCHANTS AS 
(
    SELECT DISTINCT
	MERCHANT_ID,
	MERCHANT_NAME,
	MERCHANT_CATEGORY,
	MERCHANT_TYPE,
	CITY,
	STATE,
	COUNTRY,
	MERCHANT_STATUS,
	ACCEPTS_UPI,
	ACCEPTS_CARDS,
	AVG_TICKET_SIZE,
	ONBOARDING_DATE,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
    FROM banking_data_processing.silver.bank_merchants
	WHERE IS_CURRENT = TRUE
),

STG_TRANSACTIONS AS 
(
	SELECT DISTINCT 
	TRANSACTION_ID,
	ACCOUNT_ID,
	MERCHANT_ID,
	TRANSACTION_TIMESTAMP,
	TRANSACTION_TYPE,
	AMOUNT,
	CURRENCY,
	TRANSACTION_CHANNEL,
	TRANSACTION_STATUS,
	REFERENCE_NUMBER,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.bank_transactions
 	WHERE IS_CURRENT = TRUE
)

SELECT DISTINCT 
ACC.ACCOUNT_ID,
ACC.ACCOUNT_NUMBER,
ACC.CUSTOMER_ID,
ACC.ACCOUNT_TYPE,
ACC.CURRENCY AS ACCOUNT_CURRENCY,
ACC.OPEN_DATE,
ACC.CURRENT_BALANCE,
ACC.ACCOUNT_STATUS,
ACC.CREATED_AT AS ACC_CREATED_AT,
ACC.UPDATED_AT AS ACC_UPDATED_AT,
ACC.BATCH_DATE AS ACC_BATCH_DATE,
MER.MERCHANT_ID,
MER.MERCHANT_NAME,
MER.MERCHANT_CATEGORY,
MER.MERCHANT_TYPE,
MER.CITY AS MERCHANT_CITY,
MER.STATE AS MERCHANT_STATE,
MER.COUNTRY AS MERCHANT_COUNTRY,
MER.MERCHANT_STATUS,
MER.ACCEPTS_UPI,
MER.ACCEPTS_CARDS,
MER.AVG_TICKET_SIZE,
MER.ONBOARDING_DATE,
MER.CREATED_AT AS MERCHANT_CREATED_AT,
MER.UPDATED_AT AS MERCHANT_UPDATED_AT,
MER.BATCH_DATE AS MERCHANT_BATCH_DATE,
TRANSAC.TRANSACTION_ID,
TRANSAC.TRANSACTION_TIMESTAMP,
TRANSAC.TRANSACTION_TYPE,
TRANSAC.AMOUNT AS TRANSACTION_AMOUNT,
TRANSAC.CURRENCY AS TRANSACTION_CURRENCY,
TRANSAC.TRANSACTION_CHANNEL,
TRANSAC.TRANSACTION_STATUS,
TRANSAC.REFERENCE_NUMBER AS TRANSACTION_REFERENCE_NUMBER,
TRANSAC.CREATED_AT AS TRANSAC_CREATED_AT,
TRANSAC.UPDATED_AT AS TRANSAC_UPDATED_AT,
TRANSAC.BATCH_DATE AS TRANSAC_BATCH_DATE

FROM STG_TRANSACTIONS TRANSAC

LEFT JOIN STG_ACCOUNTS ACC ON TRANSAC.ACCOUNT_ID = ACC.ACCOUNT_ID

LEFT JOIN STG_MERCHANTS MER ON MER.MERCHANT_ID = TRANSAC.MERCHANT_ID
;   
""")


# COMMAND ----------

# DBTITLE 1,Creating DIM_LOAN
#Creating DIM_LOAN
create_dim_loan = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.dim_loan 
USING DELTA
WITH STG_LOANS AS 
(
	SELECT DISTINCT 
	LOAN_ID,
	LOAN_APPLICATION_ID,
	CUSTOMER_ID,
	LOAN_TYPE,
	PRINCIPAL_AMOUNT,
	INTEREST_RATE,
	TENURE_MONTHS,
	EMI_AMOUNT,
	LOAN_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.loan_loans
	WHERE IS_CURRENT = TRUE
),

STG_LOAN_APP AS 
(
	SELECT DISTINCT 
	APPLICATION_ID,
	CUSTOMER_ID,
	APPLICATION_DATE,
	REQUESTED_AMOUNT,
	APPROVAL_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.loan_loan_applications
	WHERE IS_CURRENT = TRUE
),

STG_LOAN_COLL AS 
(
	SELECT DISTINCT 
	COLLATERAL_ID,
	LOAN_ID,
	ASSET_TYPE,
	ASSET_VALUE,
	VALUATION_DATE,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.loan_loan_collateral
	WHERE IS_CURRENT = TRUE
)

SELECT DISTINCT 
LOAN.LOAN_ID,
LOAN_APP.APPLICATION_ID AS LOAN_APPLICATION_ID,
LOAN.CUSTOMER_ID,
LOAN.LOAN_TYPE,
LOAN.PRINCIPAL_AMOUNT,
LOAN.INTEREST_RATE,
LOAN.TENURE_MONTHS,
LOAN.EMI_AMOUNT,
LOAN.LOAN_STATUS,
LOAN.CREATED_AT AS LOAN_CREATED_AT,
LOAN.UPDATED_AT AS LOAN_UPDATED_AT,
LOAN.BATCH_DATE AS LOAN_BATCH_DATE,
LOAN_APP.APPLICATION_DATE,
LOAN_APP.REQUESTED_AMOUNT,
LOAN_APP.APPROVAL_STATUS,
LOAN_APP.CREATED_AT AS LOAN_APP_CREATED_AT,
LOAN_APP.UPDATED_AT AS LOAN_APP_UPDATED_AT,
LOAN_APP.BATCH_DATE AS LOAN_APP_BATCH_DATE,
LOAN_COLL.COLLATERAL_ID,
LOAN_COLL.ASSET_TYPE,
LOAN_COLL.ASSET_VALUE,
LOAN_COLL.VALUATION_DATE,
LOAN_COLL.CREATED_AT AS LOAN_COLL_CREATED_AT,
LOAN_COLL.UPDATED_AT AS LOAN_COLL_UPDATED_AT,
LOAN_COLL.BATCH_DATE AS LOAN_COLL_BATCH_DATE
FROM STG_LOANS LOAN 

LEFT JOIN STG_LOAN_APP LOAN_APP ON LOAN_APP.APPLICATION_ID = LOAN.LOAN_APPLICATION_ID AND LOAN_APP.CUSTOMER_ID = LOAN.CUSTOMER_ID

LEFT JOIN STG_LOAN_COLL LOAN_COLL ON LOAN_COLL.LOAN_ID = LOAN.LOAN_ID
;   
""")


# COMMAND ----------

# DBTITLE 1,Creating FACT_LOAN_REPAYMENTS
#Creating FACT_LOAN_REPAYMENTS
create_fact_loan_repayments = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.fact_loan_repayments 
USING DELTA
WITH STG_LOANS AS 
(
	SELECT DISTINCT 
	LOAN_ID,
	LOAN_APPLICATION_ID,
	CUSTOMER_ID,
	LOAN_TYPE,
	PRINCIPAL_AMOUNT,
	INTEREST_RATE,
	TENURE_MONTHS,
	EMI_AMOUNT,
	LOAN_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.loan_loans
	WHERE IS_CURRENT = TRUE
),

STG_LOAN_REPAYMENTS AS 
(
	SELECT DISTINCT 
	REPAYMENT_ID,
	LOAN_ID,
	PAYMENT_DATE,
	AMOUNT_PAID,
	PAYMENT_MODE,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.loan_loan_repayments
	WHERE IS_CURRENT = TRUE
)

SELECT DISTINCT 
LOAN.LOAN_ID,
LOAN.LOAN_APPLICATION_ID,
LOAN.CUSTOMER_ID,
LOAN.LOAN_TYPE,
LOAN.PRINCIPAL_AMOUNT,
LOAN.INTEREST_RATE,
LOAN.TENURE_MONTHS,
LOAN.EMI_AMOUNT,
LOAN.LOAN_STATUS,
LOAN.CREATED_AT AS LOAN_CREATED_AT,
LOAN.UPDATED_AT AS LOAN_UPDATED_AT,
LOAN.BATCH_DATE AS LOAN_BATCH_DATE,
REPAY.REPAYMENT_ID,
REPAY.PAYMENT_DATE,
REPAY.AMOUNT_PAID,
REPAY.PAYMENT_MODE,
REPAY.CREATED_AT AS REPAY_CREATED_AT,
REPAY.UPDATED_AT AS REPAY_UPDATED_AT,
REPAY.BATCH_DATE AS REPAY_BATCH_DATE
FROM STG_LOAN_REPAYMENTS REPAY

LEFT JOIN STG_LOANS LOAN ON LOAN.LOAN_ID = REPAY.LOAN_ID
;   
""")


# COMMAND ----------

# DBTITLE 1,Creating DIM_EMPLOYEES
#Creating DIM_EMPLOYEES
create_dim_account = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.dim_employees
USING DELTA
WITH STG_EMPLOYEES AS 
(
	SELECT DISTINCT 
	EMPLOYEE_ID,
	BRANCH_ID,
	FIRST_NAME,
	LAST_NAME,
	DESIGNATION,
	DEPARTMENT,
	HIRE_DATE,
	SALARY,
	EMPLOYEE_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.org_employees
	WHERE IS_CURRENT = TRUE
),

STG_BRANCHES AS 
(
	SELECT DISTINCT 
	OB.BRANCH_ID,
	BRANCH_NAME,
	CITY,
	STATE,
	COUNTRY,
	ZIP_CODE,
	SE.EMPLOYEE_ID AS MANAGER_EMPLOYEE_ID,
	CONCAT(TRIM(SE.FIRST_NAME), ' ', TRIM(SE.LAST_NAME)) AS MANAGER_NAME,
	OPENED_DATE,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.org_branches OB
	
	LEFT JOIN 
	(
		SELECT DISTINCT 
		EMPLOYEE_ID, BRANCH_ID, FIRST_NAME, LAST_NAME, DESIGNATION 
		FROM STG_EMPLOYEES WHERE UPPER(TRIM(DESIGNATION)) = 'MANAGER'
	) SE 
	ON SE.BRANCH_ID = OB.BRANCH_ID
	
	WHERE OB.IS_CURRENT = TRUE
)

SELECT DISTINCT 
EMP.EMPLOYEE_ID,
CONCAT(TRIM(EMP.FIRST_NAME), ' ', TRIM(EMP.LAST_NAME)) AS EMPLOYEE_NAME,
EMP.DESIGNATION AS EMPLOYEE_DESIGNATION,
EMP.DEPARTMENT AS EMPLOYEE_DEPARTMENT,
EMP.HIRE_DATE AS EMPLOYEE_HIRE_DATE,
EMP.SALARY AS EMPLOYEE_SALARY_PER_ANNUM,
EMP.EMPLOYEE_STATUS,
EMP.CREATED_AT AS EMP_CREATED_AT,
EMP.UPDATED_AT AS EMP_UPDATED_AT,
EMP.BATCH_DATE AS EMP_BATCH_DATE,
BRANCH.BRANCH_ID,
BRANCH.BRANCH_NAME,
BRANCH.CITY AS BRANCH_CITY,
BRANCH.STATE AS BRANCH_STATE,
BRANCH.COUNTRY AS BRANCH_COUNTRY,
BRANCH.ZIP_CODE AS BRANCH_ZIP_CODE,
CASE WHEN EMP.EMPLOYEE_ID = BRANCH.MANAGER_EMPLOYEE_ID THEN NULL ELSE MANAGER_EMPLOYEE_ID END AS MANAGER_EMPLOYEE_ID,
CASE WHEN EMP.EMPLOYEE_ID = BRANCH.MANAGER_EMPLOYEE_ID THEN NULL ELSE BRANCH.MANAGER_NAME END AS BRANCH_MANAGER_NAME,
BRANCH.OPENED_DATE AS BRANCH_OPENED_DATE,
BRANCH.CREATED_AT AS BRANCH_CREATED_AT,
BRANCH.UPDATED_AT AS BRANCH_UPDATED_AT,
BRANCH.BATCH_DATE AS BRANCH_BATCH_DATE
FROM STG_EMPLOYEES EMP

LEFT JOIN STG_BRANCHES BRANCH ON BRANCH.BRANCH_ID = EMP.BRANCH_ID
;   
""")


# COMMAND ----------

# DBTITLE 1,Creating FACT_FRAUD_ALERTS
#Creating FACT_FRAUD_ALERTS
create_fact_fraud_alerts = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.fact_fraud_alerts 
USING DELTA
WITH STG_ACCOUNTS AS 
(
	SELECT DISTINCT 
	ACCOUNT_ID,
	CUSTOMER_ID,
	BRANCH_ID,
	ACCOUNT_NUMBER,
	ACCOUNT_TYPE,
	CURRENCY,
	OPEN_DATE,
	CURRENT_BALANCE,
	ACCOUNT_STATUS,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.bank_accounts
	WHERE IS_CURRENT = TRUE
),

STG_FRAUD_ALERTS AS 
(
	SELECT DISTINCT 
	ALERT_ID,
	TRANSACTION_ID,
	FRAUD_SCORE,
	ALERT_REASON,
	ALERT_STATUS,
	ALERT_TIMESTAMP,
	ASSIGNED_TO,
	ASSIGNEE_EMP_ID,
	RESOLUTION_DATE,
	CREATED_AT,
	UPDATED_AT,
	BATCH_DATE
	FROM banking_data_processing.silver.risk_fraud_alerts
	WHERE IS_CURRENT = TRUE
),

STG_TRANSACTIONS AS 
(
	SELECT DISTINCT 
	ACCOUNT_ID,
	TRANSACTION_ID
	FROM banking_data_processing.silver.bank_transactions
	WHERE IS_CURRENT = TRUE
),

STG_CUSTOMERS AS 
(
	SELECT DISTINCT 
	CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE,
	OCCUPATION,
	ANNUAL_INCOME,
	CUSTOMER_SINCE,
	RISK_RATING,
	CUSTOMER_STATUS,
	BATCH_DATE
	FROM banking_data_processing.silver.cust_customers
	WHERE IS_CURRENT = TRUE
)

SELECT DISTINCT 
ACC.ACCOUNT_ID,
ACC.ACCOUNT_NUMBER,
FRAUD.ALERT_ID,
TRANSAC.TRANSACTION_ID,
FRAUD.FRAUD_SCORE,
FRAUD.ALERT_REASON,
FRAUD.ALERT_STATUS,
FRAUD.ALERT_TIMESTAMP,
FRAUD.ASSIGNED_TO,
FRAUD.ASSIGNEE_EMP_ID,
FRAUD.RESOLUTION_DATE,
CUST.CUSTOMER_ID,
CONCAT(TRIM(CUST.FIRST_NAME), ' ', TRIM(CUST.LAST_NAME)) AS CUSTOMER_NAME,
CUST.EMAIL,
CUST.PHONE,
CUST.CUSTOMER_SINCE,
CUST.RISK_RATING,
CUST.CUSTOMER_STATUS,
ACC.ACCOUNT_TYPE,
ACC.CURRENCY,
ACC.OPEN_DATE,
ACC.CURRENT_BALANCE,
ACC.ACCOUNT_STATUS,
ACC.CREATED_AT AS ACC_CREATED_AT,
ACC.UPDATED_AT AS ACC_UPDATED_AT,
ACC.BATCH_DATE AS ACC_BATCH_DATE,
CUST.BATCH_DATE AS CUST_BATCH_DATE,
FRAUD.CREATED_AT AS FRAUD_CREATED_AT,
FRAUD.UPDATED_AT AS FRAUD_UPDATED_AT,
FRAUD.BATCH_DATE AS FRAUD_BATCH_DATE

FROM STG_FRAUD_ALERTS FRAUD

LEFT JOIN STG_TRANSACTIONS TRANSAC ON FRAUD.TRANSACTION_ID = TRANSAC.TRANSACTION_ID

LEFT JOIN STG_ACCOUNTS ACC ON TRANSAC.ACCOUNT_ID = ACC.ACCOUNT_ID

LEFT JOIN STG_CUSTOMERS CUST ON CUST.CUSTOMER_ID = ACC.CUSTOMER_ID
;   
""")


# COMMAND ----------

# DBTITLE 1,Creating DIM_EXCHANGE_RATES
#Creating DIM_EXCHANGE_RATES
create_dim_exchange_rates = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.dim_exchange_rates
USING DELTA
AS
SELECT DISTINCT
RATE_DATE,
CURRENCY,
CURRENCY_SYMBOL,
RATE_TO_INR,
BASE_CURRENCY
FROM banking_data_processing.silver.exchange_rates
WHERE IS_CURRENT = TRUE
;
""")

# COMMAND ----------

# DBTITLE 1,Creating DIM_DATE
create_dim_date = spark.sql("""INSERT OVERWRITE TABLE banking_data_processing.gold.dim_date
SELECT
    CAST(DATE_FORMAT(date, 'yyyyMMdd') AS STRING) AS date_id,
    date,
    YEAR(date) AS year,
    QUARTER(date) AS quarter,
    MONTH(date) AS month,
    MONTHNAME(date) AS month_name,
    DAY(date) AS day,
    DAYOFWEEK(date) AS day_of_week,
    ((DAYOFWEEK(date) + 5) % 7) + 1 AS day_of_week_iso,
    WEEKOFYEAR(date) AS week_of_year

FROM
(
    SELECT
        EXPLODE(
            SEQUENCE(
                DATE '2020-01-01',
                DATE '2030-12-31',
                INTERVAL 1 DAY
            )
        ) AS date
);
""")

# COMMAND ----------

# DBTITLE 1,Send Email with Ingestion Details
# Email with Ingestion Details
from email.message import EmailMessage
from datetime import datetime
import smtplib

recipient_email = "bankingdataplatform.project@gmail.com"

# Store these in a Databricks secret scope before running this cell.
# Example scope/key names used below:
#   scope = "email"
#   key   = "gmail_sender"
#   key   = "gmail_app_password"
sender_email = dbutils.secrets.get("email", "gmail_sender")
sender_password = dbutils.secrets.get("email", "gmail_app_password")

created_gold_tables = [
    "banking_data_processing.gold.dim_customer",
    "banking_data_processing.gold.dim_account",
    "banking_data_processing.gold.fact_transactions",
    "banking_data_processing.gold.dim_loan",
    "banking_data_processing.gold.fact_loan_repayments",
    "banking_data_processing.gold.dim_employees",
    "banking_data_processing.gold.fact_fraud_alerts",
    "banking_data_processing.gold.dim_exchange_rates",
    "banking_data_processing.gold.dim_date"
]

run_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
subject = f"Gold layer ingestion details - {run_timestamp}"
body = f"""
Hello Team,

The gold layer ingestion notebook has completed the table creation flow.

Notebook: Gold Schema - dim fact tables creation
Execution timestamp: {run_timestamp}
Target layer: banking_data_processing.gold

Tables included in this run:
- """ + "\n- ".join(created_gold_tables) + """

Please review the gold tables for downstream reporting and validation.

Regards,
Databricks Notebook Automation
"""

message = EmailMessage()
message["Subject"] = subject
message["From"] = sender_email
message["To"] = recipient_email
message.set_content(body)

with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
    smtp.starttls()
    smtp.login(sender_email, sender_password)
    smtp.send_message(message)

print(f"Ingestion details email sent successfully to {recipient_email}")