CREATE OR REPLACE VIEW ABC_BANK.AGG.DIM_HOLIDAY_CALENDAR_VW AS
SELECT DISTINCT
HOLIDAY_ID,
HOLIDAY_DATE,
COUNTRY,
STATE,
HOLIDAY_NAME,
HOLIDAY_TYPE,
IS_BANK_HOLIDAY,
CREATED_AT,
UPDATED_AT,
SOURCE_SYSTEM
FROM ABC_BANK.STG.HOLIDAY_CALENDAR;