CREATE OR REPLACE TABLE ABC_BANK.AGG.DATABRICKS_GOLD_SNOWFLAKE_AGG_LOAD_AUDIT (
    AUDIT_ID                VARCHAR(36),
    TABLE_NAME              VARCHAR(100) NOT NULL,
    SOURCE_TABLE             VARCHAR(200) NOT NULL,
    LOAD_TYPE                VARCHAR(50),
    LOAD_START_TIME          TIMESTAMP_NTZ,
    LOAD_END_TIME            TIMESTAMP_NTZ,
    ROW_COUNT                NUMBER,
    LOAD_STATUS              VARCHAR(30),
    UPDATED_FROM_DATABRICKS  TIMESTAMP_NTZ,
    ERROR_MESSAGE            VARCHAR(5000),
    CREATED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);