CREATE OR REPLACE TABLE ABC_BANK.AGG.ORG_BRANCHES
(
    BRANCH_ID               VARCHAR(20)        NOT NULL,

    BRANCH_NAME             VARCHAR(100)       NOT NULL,

    CITY                    VARCHAR(100)       NOT NULL,

    STATE                   VARCHAR(100)       NOT NULL,

    COUNTRY                 VARCHAR(100)       NOT NULL,

    ZIP_CODE                VARCHAR(15)        NOT NULL,

    MANAGER_EMPLOYEE_ID     VARCHAR(20),

    OPENED_DATE             DATE               NOT NULL,

    CREATED_AT              TIMESTAMP_NTZ      DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(50)        DEFAULT 'Enterprise System',
    BATCH_ID                VARCHAR(50),

    CONSTRAINT PK_BRANCHES
        PRIMARY KEY (BRANCH_ID),

    CONSTRAINT UQ_BRANCH_NAME
        UNIQUE (BRANCH_NAME)
);

ALTER TABLE ABC_BANK.AGG.ORG_BRANCHES
ADD CONSTRAINT FK_BRANCH_MANAGER
FOREIGN KEY (MANAGER_EMPLOYEE_ID)
REFERENCES ORG_EMPLOYEES(EMPLOYEE_ID);