CREATE OR REPLACE TABLE ABC_BANK.AGG.CUST_KYC
(
    CUSTOMER_ID             VARCHAR(20)    NOT NULL,

    PAN_NUMBER              VARCHAR(10)    NOT NULL,
    AADHAAR_NUMBER          VARCHAR(12)    NOT NULL,

    PAN_VERIFIED            BOOLEAN        NOT NULL,
    AADHAAR_VERIFIED        BOOLEAN        NOT NULL,
    ADDRESS_VERIFIED        BOOLEAN        NOT NULL,

    KYC_STATUS              VARCHAR(20)    NOT NULL,

    VERIFICATION_DATE       DATE,

    CONSTRAINT PK_KYC
        PRIMARY KEY (CUSTOMER_ID),

    CONSTRAINT FK_KYC_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUST_CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT UQ_PAN_NUMBER
        UNIQUE (PAN_NUMBER),

    CONSTRAINT UQ_AADHAAR_NUMBER
        UNIQUE (AADHAAR_NUMBER),

    CONSTRAINT CHK_KYC_STATUS
        CHECK (UPPER(KYC_STATUS) IN ('PENDING','VERIFIED','REJECTED'))
);