CREATE OR REPLACE TABLE ABC_BANK.AGG.CUST_CUSTOMERS
(
    CUSTOMER_ID         VARCHAR(20)        NOT NULL,
    FIRST_NAME          VARCHAR(50)        NOT NULL,
    LAST_NAME           VARCHAR(50)        NOT NULL,
    DOB                 DATE               NOT NULL,
    GENDER              VARCHAR(20)        NOT NULL,
    EMAIL               VARCHAR(100),
    PHONE               VARCHAR(20),
    OCCUPATION          VARCHAR(100),
    ANNUAL_INCOME       NUMBER(15,2),
    CUSTOMER_SINCE      DATE               NOT NULL,
    RISK_RATING         VARCHAR(10)        NOT NULL,
    CUSTOMER_STATUS     VARCHAR(20)        NOT NULL,

    CREATED_AT          TIMESTAMP_NTZ      DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ,
    SOURCE_SYSTEM       VARCHAR(50)        NOT NULL,
    BATCH_ID            VARCHAR(50)        NOT NULL,

    CONSTRAINT PK_CUSTOMERS
        PRIMARY KEY (CUSTOMER_ID),

    CONSTRAINT CHK_GENDER
        CHECK (UPPER(GENDER) IN ('MALE','FEMALE','NON-BINARY','PREFER NOT TO SAY')),

    CONSTRAINT CHK_RISK_RATING
        CHECK (UPPER(RISK_RATING) IN ('LOW','MEDIUM','HIGH')),

    CONSTRAINT CHK_CUSTOMER_STATUS
        CHECK (UPPER(CUSTOMER_STATUS) IN ('ACTIVE','DORMANT','CLOSED','BLOCKED')),

    CONSTRAINT CHK_ANNUAL_INCOME
        CHECK (ANNUAL_INCOME >= 0)
);